//! Build-script helpers for compiling brand icon resources into Windows binaries.
//! Vendored from `runner::core::build_resources`.
//!
//! Since `build.rs` runs in a separate compilation unit and cannot import
//! from the main crate, this file is intended to be `include!`-d from
//! `build.rs` rather than added as a `mod`.

use std::path::Path;

pub const DEFAULT_PRODUCT_NAME: &str = "local76-storm";
pub const DEFAULT_COMPANY_NAME: &str = "local76";
pub const DEFAULT_LEGAL_COPYRIGHT: &str = "Copyright \u{00A9} 2026 local76";

/// Generate a `windows_resource.rc` file that declares the ICO and a
/// standard VERSIONINFO block, and emit a `cargo:rerun-if-changed` for
/// the ICO so the build re-runs on asset changes.
pub fn write_brand_rc(
    out_path: impl AsRef<Path>,
    ico_path: &str,
    file_description: &str,
    product_name: &str,
    company_name: &str,
    legal_copyright: &str,
) -> String {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let out_abs = if out_path.as_ref().is_absolute() {
        out_path.as_ref().to_path_buf()
    } else {
        Path::new(&manifest_dir).join(out_path.as_ref())
    };

    let ico_abs = if Path::new(ico_path).is_absolute() {
        ico_path.to_string()
    } else {
        Path::new(&manifest_dir)
            .join(ico_path)
            .to_string_lossy()
            .replace('\\', "\\\\")
    };

    let rc = format!(
        r#"// Auto-generated by build.rs
// Do not edit by hand; rerun cargo to regenerate.

1 ICON "{ico_abs}"
1 VERSIONINFO
FILEVERSION 1,0,0,0
PRODUCTVERSION 1,0,0,0
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904E4"
        BEGIN
            VALUE "CompanyName",     "{company}\0"
            VALUE "FileDescription", "{file_desc}\0"
            VALUE "LegalCopyright",  "{copyright}\0"
            VALUE "ProductName",     "{product}\0"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 1252
    END
END
"#,
        company = escape_rc(company_name),
        file_desc = escape_rc(file_description),
        copyright = escape_rc(legal_copyright),
        product = escape_rc(product_name),
    );

    if let Some(parent) = out_abs.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    std::fs::write(&out_abs, rc).expect("failed to write windows_resource.rc");
    println!("cargo:rerun-if-changed={}", ico_path);
    out_abs.to_string_lossy().to_string()
}

fn escape_rc(s: &str) -> String {
    s.replace('"', "'").replace('\n', " ")
}
